### PR TITLE
Adding GPU vs CPU plots

### PR DESCRIPTION
**Pull request by AdrianoDee**
- Adding Pixel triplets workflows (.505 on CPU, .506 on GPU) for pixel validation, profiling and memchecks (.506 only)
- Adding GPU (.502, .506) vs CPU (.501,.505) validation plots for Pixel workflows

As a reference see PR `#560` at `6202cee8a23f2fc6bfb7acae61881e6722825d8c` validation [here](https://github.com/cms-patatrack/cmssw/pull/560#issuecomment-714268885)

### CODE REVIEW

**Comment by AdrianoDee** [comment]
With the new workflows the validation took approximately 4:30 h on `fu-c2a02-37-02`

**Comment by fwyzard** [comment]
Thanks for the PR !

I guess we need to cut down on some of the measurements - ideally I'd like
to go down to 1 hour or so...

Do you have a feeling of how long each step takes ?

**Comment by AdrianoDee** [comment]
Breaking it down roughly:

- release & configs set-up(s) & ~60 mins 
- the various validation reconstruction & harvesting steps ~70 mins (basically evenly split among different jobs)
- profilling ~10-15 mins
- mem/synch/init checks ~40 mins
- scans ~60 mins (10 each)

**Comment by fwyzard** [comment]
Thanks for the break down.

I've been thinking about ways to speed it up a bit, and I think that for the MC-based validation we could merge three of the workflows in a single one:
  - triplets
  - ECAL
  - HCAL

This would also help if we add particle flow later on :-)
The quadruplets would need to stay separate (unless we have a way of filtering only the quadruplets for the validation plots).

We can also try running mutiple cmsDriver in parallel to create the workflows faster.

The scan are also rather time intensive... I would prefer to keep them separate (and actually add a scan for the combined workflow ?) but maybe we can reduce the number of points (e.g. every 2 instead of every 1 thread) and jobs (3 instead of 4) while making it up increasing the number of events (we spend more time starting the jobs than actually running).

**Comment by fwyzard** [comment]
Let me know if you want to try doing any of those things :-)

**Pull request merged**
